name: 			The Gamer's Reader
description:	Landpage of "The Gamer's Reader", the best gaming news iOS app
#url: 			http://localhost:4000
url: 			http://www.thegamersreader.com

markdown: 		redcarpet
pygments: 		true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: 		Europe/Paris

collections:
    changelogs:
        output: false
